# Generated by Django 3.1.4 on 2020-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('coid', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('cid', models.IntegerField(verbose_name='文章主键')),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('text', models.TextField(blank=True, null=True, verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='文章主键')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='文章写入时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='文章修改时间')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('authorId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=200, verbose_name='分类标题')),
                ('description', models.CharField(max_length=200, verbose_name='分类描述')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章主键')),
                ('mid', models.IntegerField(verbose_name='分类主键')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=32, verbose_name='用户名（英文）')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='用户邮箱')),
                ('screenName', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
                ('group', models.CharField(default='subscriber', max_length=16, verbose_name='用户组')),
            ],
        ),
    ]
