# Generated by Django 3.1.4 on 2020-12-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=32, verbose_name='用户名（英文）')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('mail', models.CharField(max_length=200, verbose_name='用户邮箱')),
                ('screenName', models.CharField(max_length=32, verbose_name='用户名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
                ('group', models.CharField(max_length=16, verbose_name='用户组')),
            ],
        ),
    ]
