# Generated by Django 3.1.4 on 2020-12-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(default='subscriber', max_length=16, verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=200, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='screenName',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
