# Generated by Django 3.1.4 on 2020-12-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20201224_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
    ]
